You have learned in the previous lesson how to apply arithmetic operations with arrays with the same shape using element-wise operation, but what if you want to deal with arrays with different shapes? Are these operations still valid to be used? keep reading to get the answer.
This lesson will cover the following outlines:
    
1. What Is Broadcasting?
2. Broadcasting Rules

# What Is Broadcasting?

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

Refer to Figure 1

<img src="imgs/broadcasting-col-row.gif">
<center>Figure 1: Multiplication between two 1D arrays with different shapes</center>

For example, suppose that we want to add a constant vector to each row of a matrix.
First, you need to import Numpy

In [5]:
import numpy as np

In [6]:
x = np.array([[1,   2,  3], 
              [4,   5,  6], 
              [7,   8,  9]])

v = np.array([1, 2, 3])
y = x + v

x_shape = x.shape
v_shape = v.shape
y_shape = y.shape
print('x shape is', x_shape )
print('x =', x)
print('**************')
print('v shape is', v_shape )
print('v =', v)
print('**************')
print('y shape is', y_shape )
print('y =', y)


x shape is (3, 3)
x = [[1 2 3]
 [4 5 6]
 [7 8 9]]
**************
v shape is (3,)
v = [1 2 3]
**************
y shape is (3, 3)
y = [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


You can understand from the previous example that the vector v has been added to each row of the matrix x

**Note**: Adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v.
Refer to Figure2 to get visual understanding of broadcasting.
    
<center><img src="imgs/broad_sum.PNG"></center>
<br>
<br>
<center><img src="imgs/sum_result.PNG"></center>
<center>Figure 2: Adding a constant vector to each row of a matrix.</center>
    

# Broadcasting Rules

In order to use broadcasting, the size of the trailing axes for both arrays in an operation must either be:
- the same size or
- one of them must be one. 

As you can see in the prvious example the trailing axis for the first array is 3 and for the second array is 3 so they are equal and broadcasting is valid.


**Note:** In some cases, broadcasting stretches both arrays to form an output array larger than either of the initial arrays. Refer to Figure 4.
<br>
<br>
<center><img src="imgs/broad_both_strech.PNG"></center>
<center>Figure 4: Broadcasting stretches both arrays .</center>


* When the trailing dimensions of the arrays are unequal, broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition. Refer to Figure 3
<br>
<br>
<center><img src="imgs/add_mismatch.PNG"></center>
<center>Figure 3: Trailing dimensions of the arrays are unequal .</center>

## Summary

* Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.
* Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.
* In order to broadcast, the size of the trailing axes for both arrays in an operation must **either be the same size** or **one of them must be one**.
