Once your data is represented as a NumPy array, you need a way to access this data in order to either update it or get it and use it for next calculations. So how can you access array elements or how can you extract a sub-array from a NumPy array? In order to answer these questions, this article will cover the following outlines:
1. Array Indexing 
2. Array Slicing
3. Indexing VS Slicing

So let's get started.

# Array Indexing 

NumPy array items can be accessed through indexing by using the square bracket operator []. The index in NumPy arrays starts from 0, meaning that the first item has index 0, and the second item has index 1 etc. Also, negative indexes are supported in NumPy. In this case, -1 is the index of the last item, -2 is is the index of the item before the last item. Refer to Figure 1.

<br>
<br>
<center><img src="imgs/index.PNG"></center>
<center>Figure 1: Array indexing</center>

Now, let us try some examples

In [75]:
import numpy as np

In [76]:
# 1D Array
data = np.array([11, 22, 33, 44, 55])

Get data

In [77]:
data[0]

11

In [78]:
data[1]

22

In [79]:
data[25] # There is not item 25 so we will get an error

IndexError: index 25 is out of bounds for axis 0 with size 5

In [80]:
data[-1]

55

In [81]:
data[-2]

44

Update data


In [82]:
print('Before : ', data)

# Update the second item
data[1] = -5

print('After : ', data)


Before :  [11 22 33 44 55]
After :  [11 -5 33 44 55]


In [95]:
# 2D Array
data = np.array([[5, 6, 9, 3, 5], 
                 [9, 3, 6, 5, 8]])

In [96]:
data[0, 0]

5

In [97]:
data[0, 1]

6

In [98]:
data[-1, 0]

9

In [99]:
data[-1, -1]

8

# Array Slicing

By using slicing you can extract a sub array from a NumPy array. You can slice a NumPy array over any axis. Also, it can be sliced over several axes. For each axis you wish to slice over you have to specify where to start the slicing, and where to end (the item located in the end index will not be returned). You can also specify the step, which allows you to slice only every other item. For slicing, we use the square brackets and colons. Refer to Figure 2.
<br>
<br>
<center><img src="imgs/slicing.PNG"></center>
<center>Figure 2: Array slicing</center>

Now, let us try some examples.

In [123]:
# 1D Array
data = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [124]:
data[1:6:2] # Returning all the items from the index 1 to the index 6 (not included) with a step of 2

array([22, 44, 66])

In [125]:
data[1:6]  # Returning all the items from the index 1 to the index 6 (not included) with a step of 1 (Default if it is not specified)

array([22, 33, 44, 55, 66])

In [126]:
data[2:] # Returning all the items from the index 2 to the end of the array with a step of 1

array([33, 44, 55, 66, 77, 88, 99])

In [127]:
data[:4] # Returning all the items from the index 0 to the index 4 (not included) with a step of 1

array([11, 22, 33, 44])

In [128]:
data[:4:2] # Returning all the items from the index 0 to the index 4 (not included) with a step of 1

array([11, 33])

In [129]:
# 2D Array (Like 1D array but for each axis)
data = np.array([[5, 6, 9, 3, 5], 
                 [9, 3, 6, 5, 8], 
                 [1, 2, 5, 6, 3], 
                 [7, 0, 3, 6, 9], 
                 [0, 5, 8, 6, 3]])

In [130]:
data[1:4:1, 0:3:1]

array([[9, 3, 6],
       [1, 2, 5],
       [7, 0, 3]])

In [131]:
data[1:4, 0:3] # The step is 1 by default

array([[9, 3, 6],
       [1, 2, 5],
       [7, 0, 3]])

In [132]:
data[1:4:, 0:3:] # The step is 1 by default

array([[9, 3, 6],
       [1, 2, 5],
       [7, 0, 3]])

In [133]:
data[:3, :3]

array([[5, 6, 9],
       [9, 3, 6],
       [1, 2, 5]])

In [134]:
data[3:, :3]

array([[7, 0, 3],
       [0, 5, 8]])

In [135]:
data[1:4, :]   # When

array([[9, 3, 6, 5, 8],
       [1, 2, 5, 6, 3],
       [7, 0, 3, 6, 9]])

# Indexing VS Slicing

- For indexing the square bracket operator is used whereas for slicing the square brackets and colons are used.
- Indexing returns a single item (int, float, .. etc), whereas slicing returns a sub array which is a NumPy array.
- For indexing you have to specify a specific index(location) whereas in slicing you have to specify a range.

In [136]:
data = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [137]:
# Indexing
a = data[0]
print(type(a))

<class 'numpy.int32'>


In [138]:
# Slicing
a = data[0:3]
print(type(a))

<class 'numpy.ndarray'>


# Summary

Now let’s summarize what we have learned in this article:
- You need a way to access to array data in order to either update it or get it and use it for next calculations.
- You use indexing to access a single item.
- You use slicing to access a sub array of an array.
- Both positive and negative indexes are supported in NumPy array
