# What is NumPy?

NumPy, according to its official website, is the fundamental package for scientific computing in Python. It provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

<center><img src="imgs/numpy.png"></center>

NumPy is considered one of the most common libraries in Python not only because of its great features like vectorization and broadcasting which make it have C speed, but also because of being as an  essential  requirement for tons of machine learning, deep learning, and data science libraries which in turn make learning NumPy very important to continue learning the previously mentioned fields from practical perspective. 

In this lecture, we will get NumPy installed in our devices and then we will learn about the most important data structure in NumPy which is NumPy array. So let us get started. 

# Numpy Installation
<br>
<center><img src="imgs/installation.jpeg"></center>

Standard Python distribution doesn't come bundled with NumPy package, so you need to install it. The only prerequisite for installing NumPy is Python itself.

If you use pip, you can install NumPy by opening the **command prompt** and type:

pip install numpy

or from the **notebook** directly, just type and run:

!pip install numpy

Once the library is installed, we should import it in order to use it in the following cells.

In [2]:
import numpy as np

Now let us move on to understand what NumPy array is.

# NumPy Array

NumPy array is the key data structure that is available in this library. This array can be created using ndarray  class which encapsulates n-dimensional arrays of **homogeneous** data types, with many operations being performed in compiled code for performance and speed. 
So far, the world array has been mentioned several times, so what is the array?

## What is the NumPy array?

Array is a table of items (usually numbers) which have the same data type. This table could have 1 dimension, 2 dimension or in general N dimensions. 
<br>
<br>
<center><img src="imgs/d1d2d3.png"></center>

Next we will learn how to create this array using NumPy module.

## How to Create a NumPy array?

Now let us create the first NumPy array. In order to do that we will use the function **array()**:

In [3]:
# We create a 1D array by passing a list of numbers

one_d_array = np.array([2, 5, 6, 9])
print(one_d_array)
print(type(one_d_array))

[2 5 6 9]
<class 'numpy.ndarray'>


In [4]:
# We create a 2D array by passing a list of lists of numbers

two_d_array = np.array([
    [3.5, 4.0, 6.5], 
    [0.4, 0.9, 4.7]
])
print(two_d_array)
print(type(two_d_array))

[[3.5 4.  6.5]
 [0.4 0.9 4.7]]
<class 'numpy.ndarray'>


In [5]:
# We create a 3D array by passing a list of lists in which each list is a list of numbers

three_d_array = np.array(
    [
        [[7, 1], 
         [9, 3], 
         [2, 6]], 
    
        [[4, 5], 
         [0, 8], 
         [8, 4]]
    ])
print(three_d_array)
print(type(three_d_array))

[[[7 1]
  [9 3]
  [2 6]]

 [[4 5]
  [0 8]
  [8 4]]]
<class 'numpy.ndarray'>


It is clear from the previous three examples that the NumPy array is created using the **array()** function by passing a list of items as an argument. Later on we will see other functions that help create special types of array but before that we have to learn about the array attributes which will be covered in the next section.

## Array Attributes

Each array has a set of attributes describing different aspects of the array like size, data type, shape, … etc . Mainly there are five attributes which will be discussed next in details.

### Number of dimensions: 
The "dimension" is called "axis" in NumPy.

In [6]:
data = np.array([[5.2, 3.0, 4.5] ,
                 [9.1, 0.1, 0.3]])
print(data)
ndim = data.ndim
print('Number of dimensions is: ', ndim)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
Number of dimensions is:  2


Number of dimensions concept would be clearer later on when we talk about indexing.

### Shape: 
number of items in each array dimension.

In [7]:
data = np.array([[5.2, 3.0, 4.5] ,
                 [9.1, 0.1, 0.3]])
print(data)
shape = data.shape
print('The array shape is: ' , shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
The array shape is:  (2, 3)


This (2, 3) means that we have 2 items in the first dimensions and 3 items in the second dimension

### Size: 
The total number of items inside the array.

In [8]:
data = np.array([[5.2, 3.0, 4.5] ,
                 [9.1, 0.1, 0.3]])
print(data)
size = data.size
print('The total number of items in the array is: ', size, ' [item]')

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
The total number of items in the array is:  6  [item]


### Data Type: 
The data type of the array items.

In [9]:
data = np.array([[5, 3, 4] ,
                 [9, 0, 0]])
print(data)
dtype = data.dtype
print('The items data type is: ', dtype)

[[5 3 4]
 [9 0 0]]
The items data type is:  int32


In [10]:
data = np.array([[5.2, 3, 4.5] ,
                 [9.1, 0.1, 0.3]])
print(data)
dtype = data.dtype
print('The items data type is: ', dtype)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
The items data type is:  float64


It is clear from the previous two examples that NumPy array will auto-detect the data type of the passed items.

NumPy array supports a lot of data types. These types are:

<br>
<br>
<center><img src="imgs/datatypes.png"></center>

### Item Size: 
The size in bytes of each item of the array.

In [11]:
data = np.array([[5.2, 3.0, 4.5] ,
                 [9.1, 0.1, 0.3]])

print(data)
item_size = data.itemsize
print('The size in bytes of each item of the array is: ', item_size, ' [byte]')

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
The size in bytes of each item of the array is:  8  [byte]


This "8" means that each array item will reserve 8 bytes in the memory. Therefore, the array will reserve in total 6 * 8 = 48 bytes in the memory.

## Special Functions to create a NumPy array

Previously in this article, we saw how we can create a NumPy array using array() function. However, some algorithms require creating special arrays. For example, in deep learning field you might need creating an array of the shape (500, 500) with random values. Therefore, it is impossible to create such an array by using **array()** function which requires you writing manually 250000 number. Next, we will view the most common functions that help you create the special NumPy arrays.

empty(): Returns ndarray of random values having given shape, order and datatype.

In [5]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.empty((2,3), dtype=int)

array([[1951941856,        663,          0],
       [         0,     131074,          0]])

zeros(): Returns ndarray of zeros having given shape, order and datatype.

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

ones():  Returns ndarray of ones having given shape, order and datatype.

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

arange(): Returns an array of evenly spaced values having given start, stop and step values.

In [12]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
np.arange(0, 100, 10, dtype= float)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

linspace(): Returns an array of n numbers from a specific range after giving start and stop values.

In [17]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
np.linspace(1, 10, 5, dtype=int)

array([ 1,  3,  5,  7, 10])

eye(): Returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

identity(): Returns an identity array of shape n*n.

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

random.rand(): Returns random array (uniform distribution) with specific shape

In [26]:
np.random.rand(2,2)

array([[0.52151574, 0.06907968],
       [0.9919698 , 0.37972611]])

In [25]:
np.random.rand(2,2,2)

array([[[0.14464619, 0.57056709],
        [0.21795956, 0.16583718]],

       [[0.31378454, 0.30697337],
        [0.1509174 , 0.59969219]]])

random.randn(): Returns random array (normal distribution) with specific shape

In [29]:
np.random.randn(2, 2)

array([[ 0.82389185, -0.09159069],
       [ 0.82577261,  0.56706587]])

In [30]:
np.random.randn(2, 2, 2)

array([[[ 1.07827387,  1.86496917],
        [ 0.8822471 , -0.88937664]],

       [[-1.46604457,  0.32435304],
        [ 1.02868439,  0.89728447]]])

**Note**: 
- "order" parameter in the previous functions would be more clear later on when we discuss indexing in NumPy arrays.
- **eye()** and **identity()** functions do the same thing. The main difference is that with **eye()** the diagonal can may be offset, whereas **identity()** only fills the main diagonal.

# Summary

Now let’s summarize what we have learned in this article:
<br>
<br>
<center><img src="imgs/summary.jpeg"></center>
<br>

- NumPy is considered one of the most common libraries in Python because of its speed and being an essential requirement for tons of other libraries.
- Standard Python distribution doesn't come bundled with NumPy package, so you need to install it.
- NumPy array is the key data structure that is available in this library.
- The key attributes for NumPy array are number of dimensions, shape, size, itemsize  and dtype.
