# A Quick Overview to NumPy Functions

1. Universal Functions

In [1]:
import numpy as np

In [2]:
# sum for 1D array
data = np.array([56, 21, 56, 10, 6, 24, 81])
np.sum(data)

254

In [3]:
# sum with 2D array
data = np.array([[1, 2, 3, 4],
                 [1, 2, 3, 4]])
np.sum(data) # The output is a number

20

In [4]:
data = np.array([[1, 2, 3, 4],
                 [1, 2, 3, 4]])
np.sum(data, axis=0)  # Columns sum (the output is an array)

array([2, 4, 6, 8])

In [5]:
data = np.array([[1, 2, 3, 4],
                 [1, 2, 3, 4]])
np.sum(data, axis=1)  # Rows sum (the output is an array)

array([10, 10])

In [6]:
# Example
data = np.array([[1, 2, 3, 4],
                 [1, 2, 3, 4]])
data.sum(axis=1)  # Rows sum (the output is an array)

array([10, 10])

2. Reshaping Functions

In [7]:
data = np.array([[5, 6, 9, 3, 5],
                 [9, 3, 6, 5, 8],
                 [6, 1, 8, 7, 1],
                 [1, 8, 9, 3, 5]])
print(data.shape)

(4, 5)


In [8]:
reshaped_data = data.reshape(2, 5, 2)
print(reshaped_data)
print()
print(reshaped_data.shape)

[[[5 6]
  [9 3]
  [5 9]
  [3 6]
  [5 8]]

 [[6 1]
  [8 7]
  [1 1]
  [8 9]
  [3 5]]]

(2, 5, 2)


In [9]:
data = np.array([[5, 6, 9, 3, 5],
                 [9, 3, 6, 5, 8],
                 [6, 1, 8, 7, 1],
                 [1, 8, 9, 3, 5]])
print(data.shape)

(4, 5)


In [10]:
reshaped_data = data.flatten()
print(reshaped_data)
print()
print(reshaped_data.shape)

[5 6 9 3 5 9 3 6 5 8 6 1 8 7 1 1 8 9 3 5]

(20,)


In [11]:
data = np.array([[5, 6, 9, 3, 5],
                 [9, 3, 6, 5, 8],
                 [6, 1, 8, 7, 1],
                 [1, 8, 9, 3, 5]])
print(data.shape)

(4, 5)


In [12]:
reshaped_data = data.transpose()
print(reshaped_data)
print()
print(reshaped_data.shape)

[[5 9 6 1]
 [6 3 1 8]
 [9 6 8 9]
 [3 5 7 3]
 [5 8 1 5]]

(5, 4)


3. Stacking and Splitting Functions

In [13]:
arr1 = np.array([11,  22,  33,  44])
arr2 = np.array([55,  66,  77,  88])
arr = np.stack((arr1, arr2), axis=0) # The first axis is the new one
print(arr)

[[11 22 33 44]
 [55 66 77 88]]


In [14]:
arr = np.stack((arr1, arr2), axis=1) # The second axis is the new one
print(arr)

[[11 55]
 [22 66]
 [33 77]
 [44 88]]


In [15]:
# Stack horizontally
arr1 = np.array([11,  22,  33,  44])
arr2 = np.array([55,  66,  77,  88])
arr = np.hstack((arr1, arr2))
print(arr)

[11 22 33 44 55 66 77 88]


In [16]:
# Stack vertically
arr1 = np.array([11,  22,  33,  44])
arr2 = np.array([55,  66,  77,  88])
arr = np.vstack((arr1, arr2))
print(arr)

[[11 22 33 44]
 [55 66 77 88]]


In [17]:
data = np.array([[ 11,  22,  33,  44],
                 [ 55,  66,  77,  88]])

# Split vertically
sub_arrays = np.split(data, 2, axis=0)
print(sub_arrays)

[array([[11, 22, 33, 44]]), array([[55, 66, 77, 88]])]


In [18]:
# Split horizontally
sub_arrays = np.split(data, 2, axis=1)
print(sub_arrays)

[array([[11, 22],
       [55, 66]]), array([[33, 44],
       [77, 88]])]


In [19]:
# Split horizontally
data = np.array([[ 11,  22,  33,  44],
                 [ 55,  66,  77,  88]])
sub_arrays = np.hsplit(data, 2)
print(sub_arrays)

[array([[11, 22],
       [55, 66]]), array([[33, 44],
       [77, 88]])]


In [20]:
# Split vertically
data = np.array([[ 11,  22,  33,  44],
                 [ 55,  66,  77,  88]])
sub_arrays = np.vsplit(data, 2)
print(sub_arrays)

[array([[11, 22, 33, 44]]), array([[55, 66, 77, 88]])]


### Thank You