After learning how to create arrays and how to access them using indexing and slicing, now it is calculation time. NumPy array supports different types of operators that allow you to easily process the values of these arrays. In this article, you will learn about:

1. Arithmetic operators and functions
2. Logical operators
3. Vectorization

So let us get started ...

# Arithmetic operators and functions

In a lot of applications you might need to add, subtract, .. etc NumPy arrays. The good news that all of these mathematical operations are supported using the default operators that you are familiar with.

**Some important notes before we move to the real examples**:
- Arithmetic operations between multiple Numpy arrays are applied in element-wise way so you do not need to use Python loops (Refer to Figure 1).
- A new array will be created as a result of the arithmetic operation between multiple arrays.
- Most of arithmetic operations are supported by using either the standard operators or NumPy functions.




<br>
<br>
<center><img src="imgs/element-wise-production.png"></center>
    <center>Figure 1: Element-Wise production</center>

Now, let us see the supported arithmetic operators.

In [38]:
import numpy as np

**1.Compute the element-wise summation of two arrays**

**numpy.add()**

In [39]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 7, 8, 5, 3, 6])

np.add(data1, data2)

array([58, 28, 64, 15,  9, 30])

**+ Operator**

In [40]:
data1 + data2

array([58, 28, 64, 15,  9, 30])

..........................................................................

**2.Compute the element-wise subtraction of two arrays**

**numpy.subtract()**

In [41]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 7, 8, 5, 3, 6])

np.subtract(data1, data2)

array([54, 14, 48,  5,  3, 18])

**- Operator**

In [42]:
data1 - data2

array([54, 14, 48,  5,  3, 18])

..........................................................................

**3.Compute the element-wise division of two arrays**

**numpy.divide()**

In [43]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 7, 8, 5, 3, 6])

np.divide(data1, data2)

array([28.,  3.,  7.,  2.,  2.,  4.])

**/ Operator**

In [44]:
data1 / data2

array([28.,  3.,  7.,  2.,  2.,  4.])

..........................................................................

**4.Compute the element-wise multplication of two arrays**

**numpy.multiply()**

In [45]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 7, 8, 5, 3, 6])

np.multiply(data1, data2)

array([112, 147, 448,  50,  18, 144])

***Operator**

In [46]:
data1 * data2

array([112, 147, 448,  50,  18, 144])

**Important Notes** 

In [47]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 11, 8, 5, 3, 6])
data3 = np.array([2, 10, 8, 5, 3, 11])

**Note 1:** Operations like +=, -=, *= act in place and modify the existing array.

In [48]:
data1 *= data2
data1

array([112, 231, 448,  50,  18, 144])

**Note 2:** The operator priorites follow the same rules as that in Python (parentheses, exponentiation, multiplication, division, addition, subtraction)

In [49]:
res = (data1 * data2) + data3
res

array([ 226, 2551, 3592,  255,   57,  875])

For more information about mathematical functions, you can visit numpy mathematical functions documentation, [Here](https://numpy.org/doc/stable/reference/routines.math.html)

**Note 2:** Operations like comparison between multiple Numpy arrays are applied element wise. They return an array of booleans.

# Logical operators and functions

NumPy array also supports all the logical operators that allow you to easily compare between the array element

In [50]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 11, 8, 5, 3, 6])

In [51]:
data1 > data2  # You can use > < >= <= != ==

array([ True,  True,  True,  True,  True,  True])

# Vectorization 

From the previous examples we see that all of these operators are applied element-wise and covered all the array elements without using any kinds of loops, but why?
Simply because NumPy array supports what is called **Vectorization**.

**Vectorization**: is a highly optimized way of executing array operations without using for loops which in turns reduces the running and execution time of code.

Having this feature makes the NumPy array a more optimized option for doing mathematical operations over the standard Python data structures like lists.


# Summary


<br>
<br>
<center><img src="imgs/summary.jpeg"></center>

Now let’s summarize what we have learned in this lesson:
- NumPy array supports all of the mathematical and logical operators
- Mathematical and logical operators are element-wise operators.
- NumPy array supports Vectorization which makes it a  more optimized oprtion for doing mathematical operations over the standard Python data structures.

