## Element-wise Functions and Operators

You are able now to represent your data as an array, and you can access them using array indexing and slicing for the next calculations.

Do I have to use loops while working with arrays?

Arrays are important because they enable you to express batch operations on data without writing any for loops. This is usually called vectorization. Any arithmetic operations between equal-size arrays applies the operation elementwise.

**Here are some examples about element wise operations:**

In [9]:
import numpy as np

**1.Compute the element-wise summation of two arrays**

**numpy.add()**

In [10]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 7, 8, 5, 3, 6])

np.add(data1, data2)

array([58, 28, 64, 15,  9, 30])

**+ Operator**

In [11]:
data1 + data2

array([58, 28, 64, 15,  9, 30])

..........................................................................

**2.Compute the element-wise subtraction of two arrays**

**numpy.subtract()**

In [52]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 7, 8, 5, 3, 6])

np.subtract(data1, data2)

array([54, 14, 48,  5,  3, 18])

**- Operator**

In [12]:
data1 - data2

array([54, 14, 48,  5,  3, 18])

..........................................................................

**3.Compute the element-wise division of two arrays**

**numpy.divide()**

In [53]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 7, 8, 5, 3, 6])

np.divide(data1, data2)

array([28.,  3.,  7.,  2.,  2.,  4.])

**/ Operator**

In [14]:
data1 / data2

array([28.,  3.,  7.,  2.,  2.,  4.])

..........................................................................

**4.Compute the element-wise multplication of two arrays**

**numpy.multiply()**

In [54]:
data1 = np.array([56, 21, 56, 10, 6, 24])
data2 = np.array([2, 7, 8, 5, 3, 6])

np.multiply(data1, data2)

array([112, 147, 448,  50,  18, 144])

***Operator**

In [17]:
data1 * data2

array([112, 147, 448,  50,  18, 144])

**NOTE**: For more information about mathematical functions, you can visit numpy mathematical functions documentation, [Here](https://numpy.org/doc/stable/reference/routines.math.html)

## Broadcasting